
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Michael Booth", email = "michael@databooth.com.au"},
]
dependencies = [
    "jupyterlab>=4.0.2",
]
requires-python = ">=3.11"
license = {text = "MIT"}
